apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: nasi101/netflix:latest
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
      
